//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WymaTimesheetWebApp {
    
    
    public partial class ViewScreen {
        
        /// <summary>
        /// VS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm VS;
        
        /// <summary>
        /// JobsAssembliesViewTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Table JobsAssembliesViewTable;
        
        /// <summary>
<<<<<<< HEAD:WymaTimesheetWebApp/ViewScreen.aspx.designer.cs
        /// NonChargeViewTable control.
=======
        /// IPLabel control.
>>>>>>> master:WymaTimesheetWebApp/Index.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD:WymaTimesheetWebApp/ViewScreen.aspx.designer.cs
        protected global::System.Web.UI.WebControls.Table NonChargeViewTable;
=======
        protected global::System.Web.UI.WebControls.Label IPLabel;
        
        /// <summary>
        /// IPInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox IPInput;
>>>>>>> master:WymaTimesheetWebApp/Index.aspx.designer.cs
        
        /// <summary>
        /// btnDone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnDone;
        
        /// <summary>
<<<<<<< HEAD:WymaTimesheetWebApp/ViewScreen.aspx.designer.cs
        /// btnBackVS control.
=======
        /// ResourceName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ResourceName;
        
        /// <summary>
        /// ResourceNamesInput control.
>>>>>>> master:WymaTimesheetWebApp/Index.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD:WymaTimesheetWebApp/ViewScreen.aspx.designer.cs
        protected global::System.Web.UI.HtmlControls.HtmlButton btnBackVS;
=======
        protected global::System.Web.UI.WebControls.TextBox ResourceNamesInput;
>>>>>>> master:WymaTimesheetWebApp/Index.aspx.designer.cs
    }
}
